### ISSUE TITLE
Shulker Dupe Issue

### ISSUE THREAD

**Issue by WMGameLive** [JustKato/BetterShulkers#6]
I just checked your code and found that it doesn't log which shulker the player opened. It simply adds the shulker inventory back to the player's main-hand shulker. This will cause a duplication glitch if the player opens the shulker and switches the slot to another shulker.

Plugin Version: v1.2.1
Server Version: 1.21

https://github.com/user-attachments/assets/5c6e6a43-eaf1-47c0-8177-2472e04992db

**Comment by JustKato** [comment]
Working on a patch right now, thanks so much for sending out the video, it showed me exactly what was wrong!

**Comment by JustKato** [comment]
This issue has been fixed with the PR #7
